version: "3"
services:
  app:
    build: .
    ports:
      - 4001:3000
    networks:
      - app-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    networks:
      - app-network
networks:
  app-network:
